name: First workflow 
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting 
        run: |
          echo "First World"
          echo "Second World"
      - name: Print goodbye
        run: echo "Done - bye"


#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]